
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-1
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-MenuItems-16","number":68,"title":"UCSB Dining Commons Menu Item Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/68"},{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-MenuItems-15","number":67,"title":"UCSB Dining Commons Menu Items Placeholder Pages","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/67"},{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-MenuItems-14","number":66,"title":"UCSB Dining Commons Menu Items Table","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/66"},{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-MenuItems-13","number":65,"title":"UCSBDiningCommonsMenuItemForm","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/65"},{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-MenuItems-12","number":64,"title":"UCSBDiningCommonsMenuItemFixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/64"}]
