
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-1
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"rt.z-h05","number":85,"title":"rt.z Integration Tests Homework","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/85"},{"author":{"id":"U_kgDOCMuTiw","is_bot":false,"login":"ylin250","name":""},"headRefName":"Yulin-H05","number":84,"title":"Yulin h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/84"},{"author":{"id":"U_kgDOBX3i4Q","is_bot":false,"login":"Peak1260","name":"Peak"},"headRefName":"Peak-H05","number":82,"title":"H05 - Integration and E2E Testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/82"},{"author":{"id":"U_kgDOCMuTiw","is_bot":false,"login":"ylin250","name":""},"headRefName":"lastattempt","number":81,"title":"Lastattempt","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/81"},{"author":{"id":"U_kgDOCMuTiw","is_bot":false,"login":"ylin250","name":""},"headRefName":"Yulin-UCSBOrganizations","number":80,"title":"Yulin ucsb organizations","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-1/pull/80"}]
